spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/testdb?useSSL=false
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
#      ddl-auto: create
  redis:
    host: localhost
    port: 6379
#    password: password